### ISSUE TITLE
Adopt solidus_dev_support in all extensions

### ISSUE THREAD

**Issue by elia** [solidusio/solidus_dev_support#10]
This gem should be introduced to most extensions in order to both standardize and gather feedback by trying it IRL.

## solidusio-contrib

@vassalloandrea:

- [x] [`solidus_abandoned_carts`](https://github.com/solidusio-contrib/solidus_abandoned_carts/pull/19)
- [x] [`solidus_asset_variant_options`](https://github.com/solidusio-contrib/solidus_asset_variant_options/pull/38)
- [x] [`solidus_comments`](https://github.com/solidusio-contrib/solidus_comments/pull/45)
- [x] [`solidus_digital`](https://github.com/solidusio-contrib/solidus_digital/pull/10)
- [x] [`solidus_drip`](https://github.com/solidusio-contrib/solidus_drip/pull/6)
- [x] [`solidus_easypost`](https://github.com/solidusio-contrib/solidus_easypost/pull/60)
- [x] [`solidus_editor`](https://github.com/solidusio-contrib/solidus_editor/pull/44)
- [x] [`solidus_expedited_exchanges`](https://github.com/solidusio-contrib/solidus_expedited_exchanges/pull/34)

@MinasMazar:

- [x] [`solidus_gdpr`](https://github.com/solidusio-contrib/solidus_gdpr/pull/23)
- [x] [`solidus_geocoding`](https://github.com/solidusio-contrib/solidus_geocoding/pull/8)
- [x] [`solidus_globalize`](https://github.com/solidusio-contrib/solidus_globalize/pull/122)
- [x] [`solidus_multi_domain`](https://github.com/solidusio-contrib/solidus_multi_domain/pull/138)

@elia:

- [x] [`solidus_static_content`](https://github.com/solidusio-contrib/solidus_static_content/pull/60)
- [x] [`solidus_print_invoice`](https://github.com/solidusio-contrib/solidus_print_invoice/pull/37)
- [x] [`solidus_log_viewer`](https://github.com/solidusio-contrib/solidus_log_viewer/pull/27)
- [x] [`solidus_handling_fees`](https://github.com/solidusio-contrib/solidus_handling_fees/pull/11)

@aldesantis:

- [x] [`solidus_reports`](https://github.com/solidusio-contrib/solidus_reports/pull/21)
- [x] [`solidus_reviews`](https://github.com/solidusio-contrib/solidus_reviews/pull/72)
- [x] [`solidus_sale_prices`](https://github.com/solidusio-contrib/solidus_sale_prices/pull/41)
- [x] [`solidus_searchkick`](https://github.com/solidusio-contrib/solidus_searchkick/pull/8)
- [x] [`solidus_shipping_labeler`](https://github.com/solidusio-contrib/solidus_shipping_labeler/pull/9)
- [x] [`solidus_shipwire`](https://github.com/solidusio-contrib/solidus_shipwire/pull/18)
- [x] [`solidus_signifyd`](https://github.com/solidusio-contrib/solidus_signifyd/pull/43)
- [x] [`solidus_sitemap`](https://github.com/solidusio-contrib/solidus_sitemap/pull/31)

@blocknotes:

- [x] [`solidus_papertrail`](https://github.com/solidusio-contrib/solidus_papertrail/pull/35)
- [x] [`solidus_product_assembly`](https://github.com/solidusio-contrib/solidus_product_assembly/pull/81)
- [x] [`solidus_recently_viewed`](https://github.com/solidusio-contrib/solidus_recently_viewed/pull/9)
- [x] [`solidus_product_feed`](https://github.com/solidusio-contrib/solidus_product_feed/pull/48)
- [x] [`solidus_prototypes`](https://github.com/solidusio-contrib/solidus_prototypes/pull/39)
- [x] [`solidus_quiet_logistics`](https://github.com/solidusio-contrib/solidus_quiet_logistics/pull/37)
- [x] [`solidus_redirector`](https://github.com/solidusio-contrib/solidus_redirector/pull/4)
- [x] [`solidus_related_products`](https://github.com/solidusio-contrib/solidus_related_products/pull/69)
- [x] [`solidus_tax_cloud`](https://github.com/solidusio-contrib/solidus_tax_cloud/pull/34)
- [x] [`solidus_volume_pricing`](https://github.com/solidusio-contrib/solidus_volume_pricing/pull/43)
- [x] [`solidus_virtual_gift_card`](https://github.com/solidusio-contrib/solidus_virtual_gift_card/pull/65)
- [x] [`solidus_importer`](https://github.com/nebulab/solidus_importer/commit/db46b079f3647877bf8d45e3ab80fdd99c56bec4)
- [x] [`solidus_social`](https://github.com/solidusio-contrib/solidus_social/pull/71)
- [x] [`solidus_subscriptions`](https://github.com/solidusio-contrib/solidus_subscriptions/pull/89)

## solidusio

@aldesantis:

- [x] [`solidus_affirm`](https://github.com/solidusio/solidus_affirm/pull/48)
- [x] [`solidus_auth_devise`](https://github.com/solidusio/solidus_auth_devise/pull/181)

@blocknotes:

- [x] [`solidus_paypal_braintree`](https://github.com/solidusio/solidus_paypal_braintree/pull/248)
- [x] [`solidus_i18n`](https://github.com/solidusio/solidus_i18n/pull/168)

@spaghetticode:

- [x] [`solidus_stripe`](https://github.com/solidusio/solidus_stripe/pull/21)

**Comment by aldesantis** [comment]
For reference, "(GH)" here means the gem is being taken from GitHub, so once 1.0 is released we should go back and take it from RubyGems instead. "(broken)" means that... well, that the tests are broken, and the PR must be fixed.

**Comment by aldesantis** [comment]
This needs to wait until the other issues in the [1.0.0 milestone](https://github.com/solidusio-contrib/solidus_dev_support/milestone/1) are completed.

**Comment by elia** [comment]
With the merge of https://github.com/solidusio-contrib/solidus_multi_domain/pull/138 we're finally done! 🎉🎉🎉🎉👏👏👏
