### ISSUE TITLE
Consolidate labels across all extensions

### ISSUE THREAD

**Issue by aldesantis** [solidusio/solidus_dev_support#110]
I have updated the labels in this repository to match what github_changelog_generator expects and uses to generate a semantic changelog rather than a simple list of closed issues/PRs. We should make sure to adopt the same set of labels in all repositories and enforce the presence of such labels on PRs (via Mergify?). This will allow us to generate useful changelogs from the closed issues and PRs with little effort.

**Comment by chrean** [comment]
Not relevant, because we are moving extensions to the solidusio organization and @waiting-for-dev has already cleaned up labels there.
