### ISSUE TITLE
Sandbox not including extension javascripts

### ISSUE THREAD

**Issue by skukx** [solidusio/solidus_dev_support#126]
When the sandbox application is generated, it is not appending the extension javascript files
to the `all.js` in the sandbox directory:

See: https://github.com/solidusio/solidus_dev_support/blob/master/lib/solidus_dev_support/templates/extension/bin/sandbox.tt#L77

The fix would be to change the line above to look like:

```ruby
unbundled bundle exec rails generate solidus:auth:install
unbundled bundle exec rails generate ${extension_name}:install
```

**Comment by elia** [comment]
I've done the same on some extension, editing the sandbox script
