### ISSUE TITLE
Running `bin/rails-sandbox` to create a sandbox prompts rails help in the end

### ISSUE THREAD

**Issue by blocknotes** [solidusio/solidus_dev_support#168]
When I run `bin/rails-sandbox` the sandbox is created but the rails command list is shown at the end.

That's because *rails-sandbox* proxies everything to *rails*.
It was a bit confusing to me in the beginning.

Relevant code lines from **lib/solidus_dev_support/templates/extension/bin/rails-sandbox**:

```ruby
Dir.chdir app_root
exec 'bin/rails', *ARGV
```

An option could be to skip these lines when a new sandbox is created.

**Comment by elia** [comment]
`bin/rails-sandbox` is meant to run rails commands, as a side effect will create a sandbox with `bin/sandbox` if it's not already there. 

So if you need to just create the sandbox, it is better to just call `bin/sandbox`.
