### ISSUE TITLE
Add tooling for maintaining an extension's GitHub repository

### ISSUE THREAD

**Issue by aldesantis** [solidusio/solidus_dev_support#5]
When developers create a new extension, they not only have to set up the file structure, but also the Git/GitHub repository. All extension GitHub repositories share the same settings, and it would be useful to allow an extension maintainer to automatically create and configure a repository via a CLI executable provided by solidus_dev_support.

- [ ] Allow to create a local git repository
- [ ] Allow to also create a remote GH repository
- [ ] Allow to configure the remote repo
- [ ] Propose a standard way to notify github.com/solidusio-contrib maintainers about the new extension (an awesome-solidus list?)
- [ ] Give clear instructions on how to move the extension under solidusio-contrib

**Comment by chrean** [comment]
Extensions are not created very often, so I would close this one for now.
