### ISSUE TITLE
Zeitwerk::NameError in factories.rb

### ISSUE THREAD

**Issue by blocknotes** [solidusio/solidus_dev_support#76]
I think that the `factories` generator:
https://github.com/solidusio/solidus_dev_support/blob/master/lib/solidus_dev_support/templates/extension/lib/%25file_name%25/factories.rb.tt
should be updated with the extension module name (reflecting the path), otherwise, Zeitwerk raises an exception.

**Comment by aldesantis** [comment]
@blocknotes this only happens when `lib` is managed by Zeitwerk, which it shouldn't be. The solution is to remove `lib` from `config.autoload_paths` (in `engine.rb`) and require the files in `lib` manually instead.

**Comment by blocknotes** [comment]
> @blocknotes this only happens when `lib` is managed by Zeitwerk, which it shouldn't be. The solution is to remove `lib` from `config.autoload_paths` (in `engine.rb`) and requiring the files in `lib` manually instead.

This solves the issue 👍
I don't like very much having a file that doesn't respect the path - modules names match, but we can live with it 😄
