### ISSUE TITLE
Allow a custom Gemfile for local development

### ISSUE THREAD

**Issue by aldesantis** [solidusio/solidus_dev_support#9]
Some extension developers may want to use their own tools such as Pry or Byebug to develop and debug extensions. However, these shouldn't be installed automatically for all users, since everyone has their preference.

We could recommend adding the following to an extension's `Gemfile`:

```ruby
load 'Gemfile-custom'
```

By ignoring `Gemfile-custom` in Git, users will essentially have a way to use their preferred debugging tools in the extension.

## Related issues

- #7, as this may be in the base Gemfile we provide.
- The integration with solidus_cmd.

**Comment by elia** [comment]
Consider using `Gemfile.local` which seems to be quite common, or to drop the thing entirely and let maintainers just set `BUNDLE_GEMFILE=Gemfile.local`, see also https://github.com/bundler/bundler/issues/183.

**Comment by aldesantis** [comment]
`Gemfile.local` sounds good, I think we can just add it to `.gitignore` and add something like the following to the `Gemfile` we generated with the template:
```ruby
load 'Gemfile.local' if File.exists?('Gemfile.local')
```
