### ISSUE TITLE
Integrate with GitHub Releases

### ISSUE THREAD

**Issue by aldesantis** [solidusio/solidus_dev_support#93]
The default `.gem_release.yml` we are providing will NOT create a GitHub release when releasing the gem, because we are calling `gem release` together with `gem bump`, and users have no way to specify options for `gem release --github` (namely `--token`).

There are a few ways we could solve this:

- Set the `token` option in `.gem_release.yml` by asking the user for the token upfront. The problem here is that this is sensitive information, so we'd have to store it in the environment, and I'm not sure if `.gem_release.yml` can read from the environment.
- Improve gem-release itself to read the GitHub token from the environment. This should be pretty simple and we could even use the same variable name as github-changelog-generator.
- Recommend that users release new versions by running `gem bump` and `gem release` separately.

Also worth noting, github-changelog-generator [is also planning to integrate with GitHub Releases](https://github.com/github-changelog-generator/github-changelog-generator/issues/56) at some point.

**Comment by chrean** [comment]
We have just implemented a new release automation, so chances are that this issue is not relevant anymore.
