### ISSUE TITLE
Integrate Mergify

### ISSUE THREAD

**Issue by aldesantis** [solidusio/solidus_dev_support#99]
We have enabled [Mergify](https://mergify.io) in solidusio-contrib. It would be cool to experiment with it and possibly add it to our extension template, it looks like it could really help us automate PR merges and other tasks.

**Comment by peterberkenbosch** [comment]
Interesting tool. +1 for me, we can always turn it off again if it's not working for us.

**Comment by aldesantis** [comment]
We started testing Mergify in this repo with #105. Here are a few things we can use it for:

- Automatically merge PRs that pass branch protection rules
- Require PRs to specify the right labels for github_changelog_generator (bugfix, enhancement etc.)
- Require PR titles to follow a specified, changelog-friendly format
- Anything else comes to mind?

**Comment by elia** [comment]
> Require PR titles to follow a specified, changelog-friendly format

I have reservations on this one, spoken languages are usually not very well suited for specs and linters… unless is something really basic, like the length of the title.

Otherwise I think the ones you laied out are fine 👍
Going too far beyond these could impact and be discouraging for new contributors.

**Comment by aldesantis** [comment]
@elia yeah, I think I agree, it was just a random thought. 🙂

**Comment by chrean** [comment]
Not sure I'd like to automate PR merges. Our top priority at the moment is encouraging contributions from the community and improving the quality of our backlog grooming activities.
